### PR TITLE
Suggests the C++/OpenGL header-only C++ library morphologica

### PR DESCRIPTION
**Pull request by sebjameswml**
I'm submitting my own library 'morphologica' to be considered for inclusion in your awesome list.

The code is available on [Github](https://github.com/ABRG-Models/morphologica).

morphologica is used in our research group to visualize simulations in realtime. We find the ability to visualise our simulations while they run important because it allows us to observe bugs and misbehaviours in our models that would otherwise take longer to find. Because morphologica is coded in C++ and modern OpenGL, the visualization compute time is generally small in comparison with the simulation compute time. Of all the projects on the list right now, morphologica is most similar to the vastly more complex and extensive VTK. Because morphologica is much newer and smaller than VTK, it is simpler to integrate into a researcher's own C++ simulation code and yet it provides the ability to create 2D and 3D graphs and can be extended to create custom visualisations using the drawing primitives described in the [coding readme](https://github.com/ABRG-Models/morphologica/blob/main/README.coding.md). Although morphologica is relatively new, it is stable, having been in development for several years; it has a reliable CMake-driven build process and compiles on Linux and Mac.

I think it's awesome, but then, I would! I hope you think so too.

### CODE REVIEW

**Comment by nschloe** [comment]
Let's let it mature for a little longer -- 15 stars on GitHub is too few users.

Otherwise it looks neat, especially the YouTube tutorials.

One thing that's not awesome is the use of the jet/rainbow colormaps throughout the gallery, and even the title image. (See, e.g., [this text](https://blogs.mathworks.com/headlines/2018/10/10/a-dangerous-rainbow-why-colormaps-matter/).)

In my experience, C/C++ have to do an exceptional job to overcome the installation hurdle. While many modern languages have a package manager where you can simply do `[pip,cargo,...] install mypackage`, you'll always have to go through pain with C/C++ software. -- Unless it's your system package manager of course.

To attract more users, it'd perhaps be helpful to put installation instructions at the very top of the readme (and keep them as short and easy as possible), plus add a super-simple example that the user can copy-and-paste onto her machine to see if things are working.

Anyway, let's just leave this open.

**Comment by sebjameswml** [comment]
Thanks for the comments. It's fair point about the Jet colormap. It appears a lot because it happens to be the default map, although the code includes various perceptually consistent maps, too. I should change that.

I'll think about re-ordering the front readme to place an installation/getting started guide right at the start. I'd love to attract some more users of the code, but as you suggest, maybe there's just not enough demand for running numerical code on C++.

**Comment by nschloe** [comment]
> maybe there's just not enough demand for running numerical code on C++.

In HPC, it's still no competition, C/C++ is all over the place. [PETSc](https://petsc.org/) for example is amazing. So, there still is a place for numerical code in low-level languages.

For everything else, other languages have large taken over, e.g., Python or Julia. I've been deep in C++ and Fortran and frankly speaking I wouldn't want to go there again. :smiley:

**Comment by sebjameswml** [comment]
140 stars now :)

**Comment by nschloe** [comment]
Great, congrats!

**Comment by nschloe** [comment]
The linter fails because the same link is present twice.

**Comment by sebjameswml** [comment]
I've now removed the duplicate link (and also corrected the stated license for the code).

**Pull request merged**
