### PR TITLE
Add The Topoplogy ToolKit

### PR DESCRIPTION
**Pull request by CharlesGueunet**
Hello,

This PR proposes to add TTK, on open source tool that can be used as a standalone or in conjunction with VTK / ParaView for Topological Data Analysis. It is a versatile tool that brings feature like computation of Reeb graphs or Morse Smale complex, as well as Clustering techniques or some utility to compress data.

Best,
Charles

### CODE REVIEW

**Comment by nschloe** [comment]
This fits better under the visualization section. Also, new entries are added last. The text should be

> Topological data analysis and visualization.

**Comment by CharlesGueunet** [comment]
done

**Comment by nschloe** [comment]
The text still needs to be adapted. Also please separate the programming languages with a slash `/`.

**Comment by CharlesGueunet** [comment]
I am sorry, I do not understand what change you want for the text. Though it was the uppercase.
I have updated to use the '/'

**Comment by nschloe** [comment]
The term "Open-source library and software collection" is useless. All of the entries are libraries/software collections. (What's the practical difference anyway?) Also, the license is already specified.

**Comment by CharlesGueunet** [comment]
Ok, done

**Comment by nschloe** [comment]
Thanks!

**Pull request merged**
