### PR TITLE
Adding F3D

### PR DESCRIPTION
**Pull request by mwestphal**
Let me know if any improvements are needed.

### CODE REVIEW

**Comment by nschloe** [comment]
Didn't know about F3D, love it.

I want to see some commas

> Cross-platform, fast, and

Also, is "sciviz" a particular piece of software of street slang for "scientific visualization"? If the latter, let's write it out in full.

**Comment by mwestphal** [comment]
done

**Comment by nschloe** [comment]
Still missing comma before "and".

**Comment by nschloe** [comment]
Not anymore. :smile:

**Pull request merged**
